### ISSUE TITLE
Response patterns show confusion with object literals

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-objects-diagnostic#33]
From @srhoulam via Slack:

> i have noticed a lot of syntactic confusion
> parens preceding curly braces in object literals, nestings of curly braces inside others, etc
> the ones i saw who successfully assigned a function to an object attribute were very few
> i'm wondering if this confusion would be remedied by teaching objects without literal notation intially
> using the Object constructor and assigning properties using dot and bracket notation
> also demystifying object methods by first creating a function and assigning it to a variable, then using the variable as the value for the object property to store the method
> e.g.,

```
var f = function f() {};
var obj = new Object();
obj.method = f;
```

**Comment by jrhorn424** [comment]
As of now, class average stands at 66% accuracy, the lowest of any assessment so far.

**Comment by jrhorn424** [comment]
I believe we've addressed this. @gaand can you confirm?

If you think it's a good idea and we haven't addressed it, we can track it elsewhere.

**Comment by gaand** [comment]
@jrhorn424 I showed the equivalence of literals and constructors for 
`new Object()` <-> `{}`, `new Array()` <-> `[]`, and `new Function()` <-> `function(){}`.
They may see a little more in ins-and-outs.   Let's decide after we see the  js-objects-diagnostic scores?

**Comment by jrhorn424** [comment]
I dig it.

**Comment by laurenfazah** [comment]
@jrhorn424 @gaand do you two remember how this went or have a way of checking? Are there changes worth making to this portion of the diagnostic?

**Comment by gaand** [comment]
@laurenfazah Let's see what happens today, then revisit this issue.

**Comment by berziiii** [comment]
Thoughts on this @jrhorn424?

**Comment by jrhorn424** [comment]
I think we should leave this open as informational right now.

**Comment by jrhorn424** [comment]
I'm going to close this now that everyone has had a chance to read it.
